name: Template_generator
channels:
- defaults
dependencies:
- python=3.12
- numpy=1.26.4
- scipy=1.13.1
- matplotlib=3.9.2
- plotly=5.24.1
- ipywidgets=8.1.5
- nbformat=5.10.4
- IPython=8.27.0
- pandas=2.2.2
